### ISSUE TITLE
Compilation error in all programs - Below is for PointSprite

### ISSUE THREAD

**Issue by erice4** [NCCA/ParticleSystem#1]
In file included from /opt/qt/5.5/gcc_64/include/QtGui/QOpenGLContext:1:0,
                 from /opt/qt/5.5/gcc_64/include/QtGui/qopenglwindow.h:42,
                 from /opt/qt/5.5/gcc_64/include/QtGui/QOpenGLWindow:1,
                 from include/NGLScene.h:9,
                 from src/NGLScene.cpp:4:
/opt/qt/5.5/gcc_64/include/QtGui/qopenglcontext.h:49:2: warning: #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined [-Wcpp]
 #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined
  ^
/opt/qt/5.5/gcc_64/include/QtGui/qopenglcontext.h:50:2: warning: #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h [-Wcpp]
 #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h
  ^
In file included from src/NGLScene.cpp:4:0:
include/NGLScene.h:92:5: error: 'unique_ptr' in namespace 'std' does not name a type
     std::unique_ptrngl::PathCamera m_cam;
     ^
include/NGLScene.h:108:5: error: 'unique_ptr' in namespace 'std' does not name a type
     std::unique_ptr<Emitter> m_emitter1;
     ^
include/NGLScene.h:109:5: error: 'unique_ptr' in namespace 'std' does not name a type
     std::unique_ptr<Emitter> m_emitter2;
     ^
include/NGLScene.h:110:5: error: 'unique_ptr' in namespace 'std' does not name a type
     std::unique_ptr<Emitter> m_emitter3;
     ^
include/NGLScene.h:113:5: error: 'unique_ptr' in namespace 'std' does not name a type
     std::unique_ptrngl::Text m_text;
     ^
src/NGLScene.cpp: In member function 'virtual void NGLScene::initializeGL()':
src/NGLScene.cpp:63:3: error: 'm_cam' was not declared in this scope
   m_cam.reset( new ngl::PathCamera(ngl::Vec4(0,1,-0.2),"data/loop.dat",0.001));
   ^
src/NGLScene.cpp:120:3: error: 'm_emitter1' was not declared in this scope
   m_emitter1.reset(  new Emitter(ngl::Vec3(0,0,0),"textures/SmokeTest.tiff",6000));
   ^
src/NGLScene.cpp:121:3: error: 'm_emitter2' was not declared in this scope
   m_emitter2.reset(  new Emitter(ngl::Vec3(2,0,2),"textures/SmokeTest2.tiff",6000));
   ^
src/NGLScene.cpp:122:3: error: 'm_emitter3' was not declared in this scope
   m_emitter3.reset(  new Emitter(ngl::Vec3(2,0,2),"textures/SmokeTest3.tiff",6000));
   ^
src/NGLScene.cpp:142:3: error: 'm_text' was not declared in this scope
   m_text->setScreenSize(width(),height());
   ^
src/NGLScene.cpp: In member function 'virtual void NGLScene::paintGL()':
src/NGLScene.cpp:168:24: error: 'm_cam' was not declared in this scope
   MV=trans.getMatrix()_m_cam->getViewMatrix() ;
                        ^
src/NGLScene.cpp:171:31: error: 'm_emitter1' was not declared in this scope
   glBindTexture(GL_TEXTURE_2D,m_emitter1->getTextureID());
                               ^
src/NGLScene.cpp:176:31: error: 'm_emitter2' was not declared in this scope
   glBindTexture(GL_TEXTURE_2D,m_emitter2->getTextureID());
                               ^
src/NGLScene.cpp:181:31: error: 'm_emitter3' was not declared in this scope
   glBindTexture(GL_TEXTURE_2D,m_emitter3->getTextureID());
                               ^
src/NGLScene.cpp: In member function 'virtual void NGLScene::timerEvent(QTimerEvent_)':
src/NGLScene.cpp:300:3: error: 'm_emitter1' was not declared in this scope
   m_emitter1->update();
   ^
src/NGLScene.cpp:301:3: error: 'm_emitter2' was not declared in this scope
   m_emitter2->update();
   ^
src/NGLScene.cpp:302:3: error: 'm_emitter3' was not declared in this scope
   m_emitter3->update();
   ^
src/NGLScene.cpp:307:3: error: 'm_cam' was not declared in this scope
   m_cam->updateLooped();
   ^
make: **\* [obj/NGLScene.o] Error 1
12:16:20: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project PointSprite (kit: Desktop Qt 5.5.0 GCC 64bit)
When executing step "Make"

**Comment by jmacey** [comment]
Needed to include memory for the unique_ptr, seems qmake in the shell will use g++ and this doesn't automagically include it unlike clang++ on mac
